name: Build

# on:
#   push:
#     tags:
#       - '*'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build binaries
        run: npm run build
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist